// canvas/scripts/gen-nodes.mjs
// Generates canvas/src/generated/serviceNodeDefs.ts from the backend service
// descriptors (src/nodes/services/*.service.js). Run via `npm run gen:nodes`.
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { serviceDescriptors } from '../../src/nodes/services/_descriptors.js';
import { descriptorToNodeDef } from './descriptor-to-nodedef.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, '..', 'src', 'generated');
const outFile = join(outDir, 'serviceNodeDefs.ts');

const defs = serviceDescriptors.map(descriptorToNodeDef);

const body = `// GENERATED by canvas/scripts/gen-nodes.mjs — do not edit by hand.
// Run \`npm run gen:nodes\` after changing any src/nodes/services/*.service.js descriptor.
import type { NodeTypeDef } from '../components/nodes/nodeConfig';

export const GENERATED_SERVICE_DEFS: NodeTypeDef[] = ${JSON.stringify(defs, null, 2)};
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, body);
console.log(`gen:nodes wrote ${defs.length} service node def(s) to ${outFile}`);
