/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#ffb3b1',
        'on-primary': '#630d16',
        'primary-container': '#a13c3f',
        'on-primary-container': '#ffccca',
        'primary-fixed': '#ffdad8',
        'primary-fixed-dim': '#ffb3b1',
        'on-primary-fixed': '#410007',
        'on-primary-fixed-variant': '#82252a',
        'inverse-primary': '#a13c3f',
        'secondary': '#c8c5cb',
        'on-secondary': '#303035',
        'secondary-container': '#4c4b50',
        'on-secondary-container': '#bdbbc1',
        'secondary-fixed': '#e4e1e8',
        'secondary-fixed-dim': '#c8c5cb',
        'on-secondary-fixed': '#1b1b20',
        'on-secondary-fixed-variant': '#47464b',
        'tertiary': '#81d7b1',
        'on-tertiary': '#003826',
        'tertiary-container': '#006c4d',
        'on-tertiary-container': '#93eac3',
        'tertiary-fixed': '#9df4cc',
        'tertiary-fixed-dim': '#81d7b1',
        'on-tertiary-fixed': '#002115',
        'on-tertiary-fixed-variant': '#005139',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'background': '#121414',
        'on-background': '#e2e2e2',
        'surface': '#121414',
        'surface-dim': '#121414',
        'surface-bright': '#37393a',
        'surface-variant': '#333535',
        'on-surface': '#e2e2e2',
        'on-surface-variant': '#dcc0bf',
        'inverse-surface': '#e2e2e2',
        'inverse-on-surface': '#2f3131',
        'surface-tint': '#ffb3b1',
        'surface-container-lowest': '#0c0f0f',
        'surface-container-low': '#1a1c1c',
        'surface-container': '#1e2020',
        'surface-container-high': '#282a2b',
        'surface-container-highest': '#333535',
        'outline': '#a48b8a',
        'outline-variant': '#564241',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'max-width': '1440px',
      },
      fontFamily: {
        sans: ['Geist', 'system-ui', 'sans-serif'],
        mono: ['Geist Mono', 'JetBrains Mono', 'monospace'],
        'headline-lg': ['Geist'],
        'headline-md': ['Geist'],
        'headline-sm': ['Geist'],
        'body-lg': ['Geist'],
        'body-md': ['Geist'],
        'label-md': ['Geist'],
        'code-sm': ['Geist Mono', 'JetBrains Mono'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        'code-sm': ['13px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      animation: {
        'pulse-fast': 'pulse 1s cubic-bezier(0.4,0,0.6,1) infinite',
        'dash': 'dash 20s linear infinite',
      },
      keyframes: {
        dash: {
          to: { strokeDashoffset: '-1000' },
        },
      },
    },
  },
  plugins: [],
};
