import {
  Lightning,
  ChatCircleText,
  Globe,
  GitBranch,
  GitMerge,
  Sliders,
  Code,
  Timer,
  Funnel,
  ArrowsClockwise,
  TreeStructure,
  EnvelopeSimple,
  Calendar,
  Brain,
  Robot,
  MagnifyingGlass,
  Database,
  PencilSimple,
  WarningCircle,
  FileArrowDown,
  FileArrowUp,
  FolderOpen,
  Info,
  CloudArrowUp,
  Hash,
  Key,
  SlackLogo,
  DiscordLogo,
  TelegramLogo,
  GithubLogo,
  NotionLogo,
  ListChecks,
  Table,
  Graph,
  Hourglass,
  XCircle,
  HandWaving,
  Kanban,
  type Icon as PhosphorIcon,
  type IconWeight,
} from '@phosphor-icons/react';
import { getNodeDef, CATEGORY_ICON_WEIGHT } from './nodes/nodeConfig';

const ICON_MAP: Record<string, PhosphorIcon> = {
  webhook_trigger: Lightning,
  manual_trigger:  Lightning,
  form_trigger:    ListChecks,
  chat_trigger:    ChatCircleText,
  schedule_trigger: Timer,
  http_request:    Globe,
  if:              GitBranch,
  merge:           GitMerge,
  set:             Sliders,
  code:            Code,
  code_js:         Code,
  delay:           Timer,
  wait:            Hourglass,
  human_approval:  HandWaving,
  filter:          Funnel,
  loop:            ArrowsClockwise,
  sub_workflow:    TreeStructure,
  send_email:      EnvelopeSimple,
  llm_call:        Brain,
  parallel_ai:     GitBranch,
  ai_agent:        Robot,
  vector_search:   MagnifyingGlass,
  postgres_query:  Database,
  redis_get:       Lightning,
  redis_set:       PencilSimple,
  memory_read:     Brain,
  memory_write:    Brain,
  placeholder:     WarningCircle,
  read_file:       FileArrowDown,
  write_file:      FileArrowUp,
  move_binary_data: ArrowsClockwise,
  list_files:      FolderOpen,
  binary_metadata: Info,
  s3_object:       CloudArrowUp,
  datetime:        Calendar,
  crypto:          Hash,
  jwt:             Key,
  stop_error:          XCircle,
  slack_send_message: SlackLogo,
  discord_send_message: DiscordLogo,
  telegram_send_message: TelegramLogo,
  github_api:      GithubLogo,
  notion_api:      NotionLogo,
  airtable_records: Table,
  graphql_request: Graph,
  csv_parse:       Table,
  csv_stringify:   Table,
  xml_parse:       Code,
  xml_stringify:   Code,
  html_extract:    Globe,
  json_transform:  Code,
  compression:     ArrowsClockwise,
  salesforce_api:  Database,
  hubspot_api:     Funnel,
  linear_api:      Kanban,
};

export interface NodeIconProps {
  type: string;
  size?: number;
  color?: string;
}

export function NodeIcon({ type, size = 16, color }: NodeIconProps) {
  const Icon = ICON_MAP[type] ?? MagnifyingGlass;
  const category = getNodeDef(type).category;
  const weight = (CATEGORY_ICON_WEIGHT[category] ?? 'regular') as IconWeight;
  return <Icon size={size} color={color} weight={weight} />;
}
