export interface HandleDef {
  id: string;
  label?: string;
  color?: string;
  side?: 'left' | 'right' | 'bottom';
}

export interface AgentTool {
  id: string;
  name: string;
  type: string;
}

export interface NodeTypeDef {
  type: string;
  category: 'triggers' | 'core' | 'ai' | 'data';
  label: string;
  description: string;
  color: string;
  tint: NodeTint;
  serviceColor?: string;
  complex?: boolean;
  slug?: string;
  tag?: string;
  subtitle?: (config: Record<string, unknown>) => string;
  handles: {
    in: HandleDef[];
    out: HandleDef[];
    extras?: HandleDef[];
  };
  defaultConfig: Record<string, unknown>;
  fields: FieldDef[];
}

type FieldBase = {
  key: string;
  label: string;
  description?: string;
  placeholder?: string;
  required?: boolean;
};

export type FieldDef =
  | (FieldBase & { type: 'text' | 'textarea' | 'number' })
  | (FieldBase & { type: 'select'; options: { value: string; label: string; description?: string }[] })
  | (FieldBase & { type: 'assignments' })
  | (FieldBase & { type: 'conditions' })
  | (FieldBase & { type: 'code' });

// ─── v5 amber brand system ────────────────────────────────────────────────────

export const OTTO_AMBER       = '#FF6F1A';
export const OTTO_AMBER_HOVER = '#FF8A47';

// Shape encodes what a node DOES — driven by category
export const CATEGORY_SHAPE: Record<string, 'rounded' | 'circle' | 'square-soft' | 'square-tight'> = {
  triggers: 'rounded',
  ai:       'circle',
  core:     'square-soft',
  data:     'square-tight',
};

// Color encodes WHAT a node IS — per-node tint
export type NodeTint = 'amber' | 'service' | 'neutral';

// Real service brand colors — only used when tint === 'service'
export const SERVICE = {
  postgres:  '#336791',
  openai:    '#10A37F',
  anthropic: '#D97757',
  slack:     '#611F69',
  twilio:    '#F22F46',
  github:    '#1F2328',
  stripe:    '#635BFF',
  sendgrid:  '#1A82E2',
  redis:     '#DC382D',
  s3:        '#569A31',
  discord:   '#5865F2',
  telegram:  '#26A5E4',
  notion:    '#111111',
  airtable:  '#18BFFF',
  graphql:   '#E10098',
  salesforce: '#00A1E0',
  hubspot:   '#FF7A59',
  linear:    '#5E6AD2',
} as const;

// Edge colors — neutral, not category-tinted
export const EDGE_COLOR_DARK  = 'rgba(255,255,255,0.16)';
export const EDGE_COLOR_LIGHT = 'rgba(15,15,10,0.18)';

// Resolve the display color for a node, theme-aware
export function nodeColor(def: NodeTypeDef, theme: 'dark' | 'light'): string {
  if (def.tint === 'amber')   return OTTO_AMBER;
  if (def.tint === 'service') return def.serviceColor ?? '#94A3B8';
  return theme === 'dark' ? '#A1A1AA' : '#52525B';
}

// Resolve the icon-container border-radius for a node
export function nodeRadius(def: NodeTypeDef): string {
  const shape = CATEGORY_SHAPE[def.category];
  if (shape === 'circle')        return '50%';
  if (shape === 'rounded')       return '7px';
  if (shape === 'square-tight')  return '2px';
  return '4px';
}

// ─── Legacy exports — kept for backwards compatibility ────────────────────────

export const CATEGORY_COLORS: Record<string, string> = {
  triggers: OTTO_AMBER,
  core:     '#A1A1AA',
  ai:       OTTO_AMBER,
  data:     '#A1A1AA',
};

export const CATEGORY_EDGE_COLOR: Record<string, string> = {
  triggers: EDGE_COLOR_DARK,
  core:     EDGE_COLOR_DARK,
  ai:       EDGE_COLOR_DARK,
  data:     EDGE_COLOR_DARK,
};

export const CATEGORY_ICON_WEIGHT: Record<string, string> = {
  triggers: 'bold',
  core:     'bold',
  ai:       'bold',
  data:     'bold',
};

export const NODE_CATEGORIES = [
  { id: 'triggers',    label: 'TRIGGERS' },
  { id: 'core',        label: 'CORE' },
  { id: 'ai',          label: 'AI' },
  { id: 'data',        label: 'DATA' },
] as const;

export const NODE_TYPE_DEFS: NodeTypeDef[] = [

  // ─── TRIGGERS ──────────────────────────────────────────────
  {
    type: 'webhook_trigger',
    category: 'triggers',
    label: 'Webhook',
    description: 'Receive HTTP requests',
    color: OTTO_AMBER,
    tint: 'amber',
    slug: 'TRIGGER',
    tag: 'TRIGGER',
    subtitle: (c) => `${(c.method as string) || 'POST'} /${(c.path as string) || 'my-webhook'}`,
    handles: {
      in: [],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      path: 'my-webhook',
      method: 'POST',
      responseMode: 'accepted',
      responseStatus: 202,
      responseBody: '{\n  "message": "Accepted"\n}',
    },
    fields: [
      { key: 'path', label: 'Path', type: 'text' },
      { key: 'method', label: 'Method', type: 'select', options: [
        { value: 'POST', label: 'POST' },
        { value: 'GET', label: 'GET' },
        { value: 'PUT', label: 'PUT' },
        { value: 'PATCH', label: 'PATCH' },
        { value: 'DELETE', label: 'DELETE' },
        { value: 'ANY', label: 'Any method' },
      ] },
      { key: 'responseMode', label: 'Response mode', type: 'select', options: [
        { value: 'accepted', label: 'Accepted JSON' },
        { value: 'custom', label: 'Custom body' },
        { value: 'empty', label: 'Empty 204' },
      ] },
      { key: 'responseStatus', label: 'Response status', type: 'number' },
      { key: 'responseBody', label: 'Response body', type: 'code' },
    ],
  },
  {
    type: 'manual_trigger',
    category: 'triggers',
    label: 'Manual Trigger',
    description: 'Start a workflow from the canvas test/run controls',
    color: OTTO_AMBER,
    tint: 'amber',
    slug: 'MANUAL',
    tag: 'TRIGGER',
    subtitle: () => 'manual run',
    handles: {
      in: [],
      out: [{ id: 'output' }],
    },
    defaultConfig: {},
    fields: [],
  },
  {
    type: 'form_trigger',
    category: 'triggers',
    label: 'Form Trigger',
    description: 'Start a workflow from a public form submission',
    color: OTTO_AMBER,
    tint: 'amber',
    slug: 'FORM',
    tag: 'TRIGGER',
    subtitle: (c) => `/forms/${(c.path as string) || 'lead-form'}`,
    handles: {
      in: [],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      path: 'lead-form',
      title: 'Lead Form',
      description: '',
      fieldsJson: '[\n  { "name": "email", "label": "Email", "type": "email", "required": true },\n  { "name": "message", "label": "Message", "type": "textarea" }\n]',
      submitLabel: 'Submit',
      responseMessage: 'Submitted',
    },
    fields: [
      { key: 'path', label: 'Path', type: 'text' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'fieldsJson', label: 'Fields JSON', type: 'code' },
      { key: 'submitLabel', label: 'Submit label', type: 'text' },
      { key: 'responseMessage', label: 'Response message', type: 'text' },
    ],
  },
  {
    type: 'chat_trigger',
    category: 'triggers',
    label: 'Chat Trigger',
    description: 'Start a workflow from a chat-style message endpoint',
    color: OTTO_AMBER,
    tint: 'amber',
    slug: 'CHAT',
    tag: 'TRIGGER',
    subtitle: (c) => `/chat/${(c.path as string) || 'assistant'}`,
    handles: {
      in: [],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      path: 'assistant',
      sessionField: 'sessionId',
      messageField: 'message',
      welcomeText: '',
      responseMessage: 'Message accepted',
    },
    fields: [
      { key: 'path', label: 'Path', type: 'text' },
      { key: 'sessionField', label: 'Session field', type: 'text' },
      { key: 'messageField', label: 'Message field', type: 'text' },
      { key: 'welcomeText', label: 'Welcome text', type: 'textarea' },
      { key: 'responseMessage', label: 'Response message', type: 'text' },
    ],
  },
  {
    type: 'schedule_trigger',
    category: 'triggers',
    label: 'Schedule',
    description: 'Run on a durable schedule',
    color: OTTO_AMBER,
    tint: 'amber',
    slug: 'SCHEDULE',
    tag: 'TRIGGER',
    subtitle: (c) => (c.mode === 'cron'
      ? ((c.cron as string) || '0 * * * *')
      : `Every ${c.every || 15} ${c.unit || 'minutes'}`),
    handles: {
      in: [],
      out: [{ id: 'output' }],
    },
    defaultConfig: { mode: 'interval', every: 15, unit: 'minutes', cron: '0 * * * *', timezone: 'UTC' },
    fields: [],
  },

  // ─── CORE ──────────────────────────────────────────────────
  {
    type: 'http_request',
    category: 'core',
    label: 'HTTP Request',
    description: 'Call any REST API',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'HTTP',
    tag: 'ACTION',
    subtitle: (c) => `${(c.method as string) || 'GET'} · ${(c.url as string) || 'no url set'}`,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      url: '',
      method: 'GET',
      headers: [],
      body: '',
      authType: 'none',
      authKey: '',
      authValue: '',
      authUsername: '',
      authPassword: '',
    },
    fields: [],
  },
  {
    type: 'if',
    category: 'core',
    label: 'IF Condition',
    description: 'Branch on conditions',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'IF',
    tag: 'BRANCH',
    subtitle: (c) => {
      const conds = (c.conditions as unknown[]) || [];
      return `${conds.length} condition${conds.length !== 1 ? 's' : ''}`;
    },
    complex: true,
    handles: {
      in: [{ id: 'input' }],
      out: [
        { id: 'true',  label: 'true',  color: '#22c55e' },
        { id: 'false', label: 'false', color: '#ef4444' },
      ],
    },
    defaultConfig: { conditions: [{ left: 'confidence', operator: '>=', right: '0.75' }], combinator: 'and' },
    fields: [{ key: 'conditions', label: 'Conditions', type: 'conditions' }],
  },
  {
    type: 'merge',
    category: 'core',
    label: 'Merge',
    description: 'Combine parallel branches',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'MERGE',
    tag: 'MERGE',
    subtitle: (c) => (c.mode as string) || 'merge-object',
    complex: true,
    handles: {
      in: [
        { id: 'in1', label: 'input 1' },
        { id: 'in2', label: 'input 2' },
        { id: 'in3', label: 'input 3' },
      ],
      out: [{ id: 'output' }],
    },
    defaultConfig: { mode: 'merge-object' },
    fields: [
      { key: 'mode', label: 'Mode', type: 'select', options: [{ value: 'merge-object', label: 'Merge Object' }, { value: 'collect-array', label: 'Collect Array' }] },
    ],
  },
  {
    type: 'set',
    category: 'core',
    label: 'Set / Transform',
    description: 'Shape and rename fields',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'SET',
    tag: 'ACTION',
    subtitle: (c) => {
      const a = (c.assignments as unknown[]) || [];
      return `${a.length} field${a.length !== 1 ? 's' : ''}`;
    },
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: { mode: 'set', assignments: [] },
    fields: [
      { key: 'mode', label: 'Mode', type: 'select', options: [{ value: 'set', label: 'Set only' }, { value: 'merge', label: 'Merge with input' }] },
      { key: 'assignments', label: 'Assignments', type: 'assignments' },
    ],
  },
  {
    type: 'code',
    category: 'core',
    label: 'Code',
    description: 'Run sandboxed code',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'CODE',
    tag: 'CODE',
    subtitle: (c) => (c.language as string) || 'javascript',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      language: 'javascript',
      version: '18.x',
      code: 'return input;',
      timeoutMs: 5000,
      memoryLimitMb: 128,
      stdinMode: 'json',
    },
    fields: [{ key: 'code', label: 'Code', type: 'code' }],
  },
  {
    type: 'wait',
    category: 'core',
    label: 'Wait',
    description: 'Suspend execution until a timer, webhook, or form resumes it',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'WAIT',
    tag: 'WAIT',
    subtitle: (c) => c.wait_type === 'time' ? `${c.duration_seconds || 60}s` : (c.wait_type as string || 'time'),
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: { wait_type: 'time', duration_seconds: 60 },
    fields: [
      { key: 'wait_type', label: 'Wait for', type: 'select', options: [
        { value: 'time', label: 'Timer', description: 'Resume after a fixed duration' },
        { value: 'webhook', label: 'Webhook', description: 'Resume when a URL is called' },
        { value: 'form', label: 'Form', description: 'Resume when a form is submitted' },
      ] },
      { key: 'duration_seconds', label: 'Duration (seconds)', type: 'number', placeholder: '60' },
      { key: 'timeout_seconds', label: 'Timeout (seconds)', type: 'number', placeholder: 'optional' },
      { key: 'resume_authentication', label: 'Resume auth', type: 'select', options: [
        { value: 'none', label: 'None' },
        { value: 'jwt', label: 'JWT' },
      ] },
      { key: 'form_path', label: 'Form path', type: 'text', placeholder: '/my-form' },
    ],
  },
  {
    type: 'human_approval',
    category: 'core',
    label: 'Human Approval',
    description: 'Pause execution until a human approves or rejects',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'APPROVE',
    tag: 'WAIT',
    subtitle: (c) => (c.subject as string) || 'Approval required',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      subject: '',
      message: '',
      approvers: '',
      timeoutHours: 24,
    },
    fields: [
      { key: 'subject', label: 'Subject', type: 'text', placeholder: 'Approve this action?', required: true },
      { key: 'message', label: 'Message', type: 'textarea', placeholder: 'Describe what needs approval...' },
      { key: 'approvers', label: 'Approvers', type: 'text', placeholder: 'email@example.com, another@example.com' },
      { key: 'timeoutHours', label: 'Timeout (hours)', type: 'number', placeholder: '24' },
    ],
  },
  {
    type: 'delay',
    category: 'core',
    label: 'Delay',
    description: 'Wait before continuing',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'DELAY',
    tag: 'DELAY',
    subtitle: (c) => `${c.amount || 1000} ${c.unit || 'ms'}`,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: { amount: 1000, unit: 'ms' },
    fields: [
      { key: 'amount', label: 'Amount', type: 'number' },
      { key: 'unit', label: 'Unit', type: 'select', options: [{ value: 'ms', label: 'Milliseconds' }, { value: 's', label: 'Seconds' }, { value: 'm', label: 'Minutes' }] },
    ],
  },
  {
    type: 'stop_error',
    category: 'core',
    label: 'Stop and Error',
    description: 'Halt the workflow with a custom error message',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'STOP',
    tag: 'CONTROL',
    subtitle: (c) => (c.message as string) || 'Workflow stopped',
    handles: {
      in: [{ id: 'input' }],
      out: [],
    },
    defaultConfig: { message: '' },
    fields: [
      { key: 'message', label: 'Error message', type: 'textarea', placeholder: 'Something went wrong' },
    ],
  },
  {
    type: 'filter',
    category: 'core',
    label: 'Filter',
    description: 'Drop items that don\'t match',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'FILTER',
    tag: 'FILTER',
    subtitle: (c) => {
      const conds = (c.conditions as unknown[]) || [];
      return `${conds.length} condition${conds.length !== 1 ? 's' : ''}`;
    },
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: { conditions: [] },
    fields: [{ key: 'conditions', label: 'Keep when', type: 'conditions' }],
  },
  {
    type: 'loop',
    category: 'core',
    label: 'Loop',
    description: 'Iterate over an array',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'LOOP',
    tag: 'LOOP',
    subtitle: (c) => `over ${(c.over as string) || 'items'}`,
    complex: true,
    handles: {
      in: [{ id: 'input' }],
      out: [
        { id: 'loop', label: 'loop' },
        { id: 'done', label: 'done' },
      ],
    },
    defaultConfig: { over: 'input.items', limit: 100 },
    fields: [
      { key: 'over', label: 'Array path', type: 'text' },
      { key: 'limit', label: 'Max iterations', type: 'number' },
    ],
  },
  {
    type: 'sub_workflow',
    category: 'core',
    label: 'Sub-workflow',
    description: 'Call another workflow',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'SUB',
    tag: 'SUB',
    subtitle: (c) => (c.workflowId as string) || 'not configured',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: { workflowId: '' },
    fields: [{ key: 'workflowId', label: 'Workflow ID', type: 'text' }],
  },
  {
    type: 'send_email',
    category: 'core',
    label: 'Send Email',
    description: 'Send an email via SMTP',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'EMAIL',
    tag: 'ACTION',
    subtitle: (c) => `to ${(c.to as string) || 'not set'}`,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: { to: '', subject: '', body: '' },
    fields: [
      { key: 'to', label: 'To', type: 'text' },
      { key: 'subject', label: 'Subject', type: 'text' },
      { key: 'body', label: 'Body', type: 'textarea' },
    ],
  },
  {
    type: 'datetime',
    category: 'core',
    label: 'DateTime',
    description: 'Parse, format, add, subtract, or compare dates',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'DATE',
    tag: 'UTILITY',
    subtitle: (c) => (c.operation as string) || 'now',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      operation: 'now',
      value: '{{ input.date }}',
      inputFormat: 'auto',
      outputFormat: 'iso',
      addAmount: 1,
      addUnit: 'days',
      diffUnit: 'days',
      timezone: '',
    },
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { value: 'now', label: 'Now' },
        { value: 'format', label: 'Format' },
        { value: 'parse', label: 'Parse' },
        { value: 'add', label: 'Add' },
        { value: 'subtract', label: 'Subtract' },
        { value: 'diff', label: 'Difference' },
        { value: 'toTimezone', label: 'To timezone' },
      ] },
      { key: 'value', label: 'Value', type: 'text' },
      { key: 'inputFormat', label: 'Input format', type: 'select', options: [
        { value: 'auto', label: 'Auto' },
        { value: 'iso', label: 'ISO/date string' },
        { value: 'unix', label: 'Unix seconds' },
        { value: 'unixMs', label: 'Unix milliseconds' },
      ] },
      { key: 'outputFormat', label: 'Output format', type: 'text' },
      { key: 'addAmount', label: 'Add/subtract amount', type: 'number' },
      { key: 'addUnit', label: 'Add/subtract unit', type: 'select', options: [
        { value: 'seconds', label: 'Seconds' },
        { value: 'minutes', label: 'Minutes' },
        { value: 'hours', label: 'Hours' },
        { value: 'days', label: 'Days' },
        { value: 'weeks', label: 'Weeks' },
        { value: 'months', label: 'Months' },
        { value: 'years', label: 'Years' },
      ] },
      { key: 'diffUnit', label: 'Diff unit', type: 'select', options: [
        { value: 'milliseconds', label: 'Milliseconds' },
        { value: 'seconds', label: 'Seconds' },
        { value: 'minutes', label: 'Minutes' },
        { value: 'hours', label: 'Hours' },
        { value: 'days', label: 'Days' },
        { value: 'weeks', label: 'Weeks' },
        { value: 'months', label: 'Months' },
        { value: 'years', label: 'Years' },
      ] },
      { key: 'timezone', label: 'Timezone', type: 'text' },
    ],
  },
  {
    type: 'crypto',
    category: 'core',
    label: 'Crypto',
    description: 'Hash, HMAC, encode, decode, or generate secure values',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'HASH',
    tag: 'UTILITY',
    subtitle: (c) => (c.operation as string) || 'sha256',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: { operation: 'sha256', value: '{{ input.value }}', secret: '', encoding: 'hex', length: 16 },
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { value: 'md5', label: 'MD5' },
        { value: 'sha1', label: 'SHA-1' },
        { value: 'sha256', label: 'SHA-256' },
        { value: 'sha512', label: 'SHA-512' },
        { value: 'hmac-sha256', label: 'HMAC SHA-256' },
        { value: 'hmac-sha512', label: 'HMAC SHA-512' },
        { value: 'base64-encode', label: 'Base64 encode' },
        { value: 'base64-decode', label: 'Base64 decode' },
        { value: 'uuid', label: 'UUID' },
        { value: 'random-bytes', label: 'Random bytes' },
      ] },
      { key: 'value', label: 'Value', type: 'text' },
      { key: 'secret', label: 'HMAC secret', type: 'text' },
      { key: 'encoding', label: 'Encoding', type: 'select', options: [
        { value: 'hex', label: 'Hex' },
        { value: 'base64', label: 'Base64' },
      ] },
      { key: 'length', label: 'Random byte length', type: 'number' },
    ],
  },
  {
    type: 'jwt',
    category: 'core',
    label: 'JWT',
    description: 'Sign, verify, or decode JSON Web Tokens',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'JWT',
    tag: 'UTILITY',
    subtitle: (c) => `${(c.operation as string) || 'decode'} ${(c.algorithm as string) || 'HS256'}`,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      operation: 'decode',
      payload: '{\n  "sub": "{{ input.userId }}"\n}',
      token: '{{ input.token }}',
      secret: '',
      algorithm: 'HS256',
      expiresIn: '',
    },
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { value: 'decode', label: 'Decode' },
        { value: 'verify', label: 'Verify' },
        { value: 'sign', label: 'Sign' },
      ] },
      { key: 'payload', label: 'Payload JSON', type: 'code' },
      { key: 'token', label: 'Token', type: 'textarea' },
      { key: 'secret', label: 'Secret', type: 'text' },
      { key: 'algorithm', label: 'Algorithm', type: 'select', options: [
        { value: 'HS256', label: 'HS256' },
        { value: 'HS384', label: 'HS384' },
        { value: 'HS512', label: 'HS512' },
      ] },
      { key: 'expiresIn', label: 'Expires in', type: 'text' },
    ],
  },
  {
    type: 'slack_send_message',
    category: 'core',
    label: 'Slack Send Message',
    description: 'Post a message to a Slack channel',
    color: SERVICE.slack,
    tint: 'service',
    serviceColor: SERVICE.slack,
    slug: 'SLACK',
    tag: 'MESSAGE',
    subtitle: (c) => `to ${(c.channel as string) || 'channel'}`,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      credentialId: '',
      token: '',
      channel: '',
      text: '{{ input.text }}',
      blocksJson: '',
    },
    fields: [
      { key: 'credentialId', label: 'Credential', type: 'text' },
      { key: 'token', label: 'Bot token override', type: 'text' },
      { key: 'channel', label: 'Channel', type: 'text' },
      { key: 'text', label: 'Text', type: 'textarea' },
      { key: 'blocksJson', label: 'Blocks JSON', type: 'code' },
    ],
  },
  {
    type: 'discord_send_message',
    category: 'core',
    label: 'Discord Send Message',
    description: 'Send a message through a Discord webhook',
    color: SERVICE.discord,
    tint: 'service',
    serviceColor: SERVICE.discord,
    slug: 'DISC',
    tag: 'MESSAGE',
    subtitle: (c) => (c.webhookUrl as string) ? 'webhook configured' : 'webhook required',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      credentialId: '',
      operation: 'send_message',
      webhookUrl: '',
      content: '{{ input.text }}',
      username: '',
      embedsJson: '',
      botToken: '',
      guildId: '',
      channelId: '',
      limit: 50,
    },
    fields: [
      { key: 'credentialId', label: 'Credential', type: 'text' },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { value: 'send_message', label: 'Send message (webhook)' },
        { value: 'send_embed', label: 'Send embed (webhook)' },
        { value: 'get_guild_channels', label: 'Get guild channels (bot)' },
        { value: 'get_messages', label: 'Get channel messages (bot)' },
      ] },
      { key: 'webhookUrl', label: 'Webhook URL', type: 'text' },
      { key: 'content', label: 'Content', type: 'textarea' },
      { key: 'username', label: 'Username override', type: 'text' },
      { key: 'embedsJson', label: 'Embeds JSON', type: 'code' },
      { key: 'botToken', label: 'Bot token', type: 'text' },
      { key: 'guildId', label: 'Guild ID', type: 'text' },
      { key: 'channelId', label: 'Channel ID', type: 'text' },
      { key: 'limit', label: 'Message limit', type: 'number' },
    ],
  },
  {
    type: 'telegram_send_message',
    category: 'core',
    label: 'Telegram Send Message',
    description: 'Send a message with a Telegram bot',
    color: SERVICE.telegram,
    tint: 'service',
    serviceColor: SERVICE.telegram,
    slug: 'TG',
    tag: 'MESSAGE',
    subtitle: (c) => `chat ${(c.chatId as string) || 'required'}`,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      credentialId: '',
      operation: 'send_message',
      botToken: '',
      chatId: '',
      text: '{{ input.text }}',
      parseMode: '',
      photo: '',
      caption: '',
      offset: '',
      limit: 100,
    },
    fields: [
      { key: 'credentialId', label: 'Credential', type: 'text' },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { value: 'send_message', label: 'Send message' },
        { value: 'send_photo', label: 'Send photo' },
        { value: 'get_updates', label: 'Get updates' },
        { value: 'get_chat', label: 'Get chat info' },
      ] },
      { key: 'botToken', label: 'Bot token override', type: 'text' },
      { key: 'chatId', label: 'Chat ID', type: 'text' },
      { key: 'text', label: 'Text', type: 'textarea' },
      { key: 'parseMode', label: 'Parse mode', type: 'select', options: [
        { value: '', label: 'None' },
        { value: 'MarkdownV2', label: 'MarkdownV2' },
        { value: 'HTML', label: 'HTML' },
      ] },
      { key: 'photo', label: 'Photo (file_id or URL)', type: 'text' },
      { key: 'caption', label: 'Caption', type: 'text' },
      { key: 'offset', label: 'Offset (get_updates)', type: 'number' },
      { key: 'limit', label: 'Limit', type: 'number' },
    ],
  },

  {
    type: 'stripe_api',
    category: 'core',
    label: 'Stripe API',
    description: 'Create payment intents, manage customers',
    color: SERVICE.stripe,
    tint: 'service',
    serviceColor: SERVICE.stripe,
    slug: 'STRIPE',
    tag: 'PAYMENT',
    subtitle: (c) => (c.operation as string) || 'create_payment_intent',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      credentialId: '',
      apiKey: '',
      operation: 'create_payment_intent',
      amount: '',
      currency: 'usd',
      metadataJson: '',
      paymentIntentId: '',
      customerId: '',
      email: '',
      name: '',
      limit: 10,
    },
    fields: [
      { key: 'credentialId', label: 'Credential', type: 'text' },
      { key: 'apiKey', label: 'Secret key override', type: 'text' },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { value: 'create_payment_intent', label: 'Create payment intent' },
        { value: 'get_payment_intent',    label: 'Get payment intent' },
        { value: 'list_customers',        label: 'List customers' },
        { value: 'create_customer',       label: 'Create customer' },
        { value: 'get_customer',          label: 'Get customer' },
      ] },
      { key: 'amount',          label: 'Amount (cents)',    type: 'number' },
      { key: 'currency',        label: 'Currency',          type: 'text' },
      { key: 'metadataJson',    label: 'Metadata JSON',     type: 'code' },
      { key: 'paymentIntentId', label: 'Payment Intent ID', type: 'text' },
      { key: 'customerId',      label: 'Customer ID',       type: 'text' },
      { key: 'email',           label: 'Email',             type: 'text' },
      { key: 'name',            label: 'Name',              type: 'text' },
      { key: 'limit',           label: 'List limit',        type: 'number' },
    ],
  },
  {
    type: 'sendgrid_email',
    category: 'core',
    label: 'SendGrid Email',
    description: 'Send transactional email or add marketing contacts',
    color: SERVICE.sendgrid,
    tint: 'service',
    serviceColor: SERVICE.sendgrid,
    slug: 'SG',
    tag: 'EMAIL',
    subtitle: (c) => c.operation === 'add_contact'
      ? `add ${(c.email as string) || 'contact'}`
      : `to ${(c.to as string) || 'recipient'}`,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      credentialId: '',
      apiKey: '',
      operation: 'send_email',
      to: '',
      from: '',
      subject: '',
      text: '{{ input.text }}',
      html: '',
      email: '',
      firstName: '',
      lastName: '',
    },
    fields: [
      { key: 'credentialId', label: 'Credential', type: 'text' },
      { key: 'apiKey',       label: 'API key override', type: 'text' },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { value: 'send_email',  label: 'Send email' },
        { value: 'add_contact', label: 'Add marketing contact' },
      ] },
      { key: 'to',        label: 'To email',   type: 'text' },
      { key: 'from',      label: 'From email', type: 'text' },
      { key: 'subject',   label: 'Subject',    type: 'text' },
      { key: 'text',      label: 'Plain text', type: 'textarea' },
      { key: 'html',      label: 'HTML body',  type: 'code' },
      { key: 'email',     label: 'Contact email',      type: 'text' },
      { key: 'firstName', label: 'Contact first name', type: 'text' },
      { key: 'lastName',  label: 'Contact last name',  type: 'text' },
    ],
  },
  {
    type: 'twilio_sms',
    category: 'core',
    label: 'Twilio SMS',
    description: 'Send SMS messages and query message history',
    color: SERVICE.twilio,
    tint: 'service',
    serviceColor: SERVICE.twilio,
    slug: 'TWILIO',
    tag: 'SMS',
    subtitle: (c) => c.operation === 'list_messages'
      ? 'list messages'
      : `to ${(c.to as string) || 'number'}`,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      credentialId: '',
      accountSid: '',
      authToken: '',
      operation: 'send_sms',
      to: '',
      from: '',
      body: '{{ input.text }}',
      messageSid: '',
      pageSize: 20,
    },
    fields: [
      { key: 'credentialId', label: 'Credential',          type: 'text' },
      { key: 'accountSid',   label: 'Account SID override', type: 'text' },
      { key: 'authToken',    label: 'Auth token override',  type: 'text' },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { value: 'send_sms',      label: 'Send SMS' },
        { value: 'get_message',   label: 'Get message' },
        { value: 'list_messages', label: 'List messages' },
      ] },
      { key: 'to',         label: 'To number',   type: 'text' },
      { key: 'from',       label: 'From number', type: 'text' },
      { key: 'body',       label: 'Message body', type: 'textarea' },
      { key: 'messageSid', label: 'Message SID',  type: 'text' },
      { key: 'pageSize',   label: 'Page size',    type: 'number' },
    ],
  },

  // ─── AI ────────────────────────────────────────────────────
  {
    type: 'llm_call',
    category: 'ai',
    label: 'LLM Call',
    description: 'Call any language model',
    color: OTTO_AMBER,
    tint: 'amber',
    slug: 'LLM',
    tag: 'LLM',
    subtitle: (c) => `${(c.provider as string) || 'openai'} · ${(c.model as string) || 'gpt-4o-mini'}`,
    complex: true,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: { provider: 'openai', model: 'gpt-4o-mini', apiKey: '', systemPrompt: '', userPrompt: '{{ input.message }}', temperature: 0.7, maxTokens: 1000 },
    fields: [
      { key: 'provider', label: 'Provider', type: 'select', options: [{ value: 'openai', label: 'OpenAI' }, { value: 'anthropic', label: 'Anthropic' }, { value: 'openrouter', label: 'OpenRouter' }] },
      { key: 'model', label: 'Model', type: 'text' },
      { key: 'systemPrompt', label: 'System Prompt', type: 'textarea' },
      { key: 'userPrompt', label: 'User Prompt', type: 'textarea' },
      { key: 'temperature', label: 'Temperature (0–1)', type: 'number' },
      { key: 'maxTokens', label: 'Max Tokens', type: 'number' },
    ],
  },
  {
    type: 'parallel_ai',
    category: 'ai',
    label: 'Parallel AI',
    description: 'Fan out one prompt to multiple models at once',
    color: OTTO_AMBER,
    tint: 'amber',
    slug: 'FAN',
    tag: 'PARALLEL',
    subtitle: (c) => `${(c.mode as string) || 'all'} · ${(c.timeoutMs as number) || 60000}ms`,
    complex: true,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      targetsJson: JSON.stringify([
        { id: 'openai_fast', provider: 'openai', model: 'gpt-4o-mini', userPrompt: '{{ input.message }}' },
        { id: 'anthropic_fast', provider: 'anthropic', model: 'claude-3-5-haiku-latest', userPrompt: '{{ input.message }}' },
      ], null, 2),
      systemPrompt: '',
      userPrompt: '{{ input.message }}',
      temperature: 0.7,
      maxTokens: 1000,
      timeoutMs: 60000,
      failureMode: 'all_failed',
    },
    fields: [
      { key: 'targetsJson', label: 'Targets JSON', type: 'code' },
      { key: 'systemPrompt', label: 'Default system prompt', type: 'textarea' },
      { key: 'userPrompt', label: 'Default user prompt', type: 'textarea' },
      { key: 'temperature', label: 'Default temperature', type: 'number' },
      { key: 'maxTokens', label: 'Default max tokens', type: 'number' },
      { key: 'timeoutMs', label: 'Branch timeout ms', type: 'number' },
      { key: 'failureMode', label: 'Failure mode', type: 'select', options: [
        { value: 'all_failed', label: 'Fail only if all branches fail' },
        { value: 'any_failed', label: 'Fail if any branch fails' },
        { value: 'never', label: 'Never fail from branch errors' },
      ] },
    ],
  },
  {
    type: 'ai_agent',
    category: 'ai',
    label: 'AI Agent',
    description: 'Autonomous LLM agent with tools',
    color: OTTO_AMBER,
    tint: 'amber',
    slug: 'AGENT',
    tag: 'MAIN',
    subtitle: (c) => `Autonomous · ${(c.model as string) || 'gpt-4o'}`,
    complex: true,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      model: 'gpt-4o',
      systemPrompt: 'You are a helpful assistant.',
      tools: [
        { id: 't1', name: 'CRM lookup',         type: 'http_request'   },
        { id: 't2', name: 'Customer DB',         type: 'postgres_query' },
        { id: 't3', name: 'Past conversations',  type: 'memory_read'    },
        { id: 't4', name: 'Calculator',          type: 'code'           },
      ],
      maxSteps: 10,
    },
    fields: [
      { key: 'model', label: 'Model', type: 'text' },
      { key: 'systemPrompt', label: 'System Prompt', type: 'textarea' },
      { key: 'maxSteps', label: 'Max steps', type: 'number' },
    ],
  },
  {
    type: 'memory_read',
    category: 'ai',
    label: 'Memory Read',
    description: 'Retrieve semantic or session memory',
    color: OTTO_AMBER,
    tint: 'amber',
    slug: 'MEM-R',
    tag: 'MEMORY',
    subtitle: (c) => (c.mode as string) || 'semantic',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      mode: 'semantic',
      query: '{{ input.text }}',
      sessionId: '{{ input.sessionId }}',
      category: '',
      topK: 5,
      minScore: 0,
    },
    fields: [],
  },
  {
    type: 'memory_write',
    category: 'ai',
    label: 'Memory Write',
    description: 'Persist patterns, interactions, or summaries',
    color: OTTO_AMBER,
    tint: 'amber',
    slug: 'MEM-W',
    tag: 'MEMORY',
    subtitle: (c) => (c.mode as string) || 'pattern',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      mode: 'pattern',
      content: '{{ input.text }}',
      category: 'general',
      sessionId: '{{ input.sessionId }}',
      inputText: '{{ input.question }}',
      outputText: '{{ input.answer }}',
      summary: '{{ input.summary }}',
      confidence: 1,
    },
    fields: [],
  },
  {
    type: 'vector_search',
    category: 'ai',
    label: 'Vector Search',
    description: 'Semantic similarity search',
    color: OTTO_AMBER,
    tint: 'amber',
    slug: 'VEC',
    tag: 'VEC',
    subtitle: (c) => (c.collection as string) || 'memory',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: { query: '{{ input.text }}', collection: 'memory', topK: 5 },
    fields: [
      { key: 'query', label: 'Query', type: 'text' },
      { key: 'collection', label: 'Collection', type: 'text' },
      { key: 'topK', label: 'Top K', type: 'number' },
    ],
  },

  // ─── DATA ──────────────────────────────────────────────────
  {
    type: 'github_api',
    category: 'data',
    label: 'GitHub API',
    description: 'Call GitHub REST API endpoints',
    color: SERVICE.github,
    tint: 'service',
    serviceColor: SERVICE.github,
    slug: 'GH',
    tag: 'API',
    subtitle: (c) => `${(c.method as string) || 'GET'} ${(c.path as string) || '/user'}`,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      credentialId: '',
      token: '',
      operation: 'generic',
      owner: '',
      repo: '',
      method: 'GET',
      path: '/user',
      body: '{}',
    },
    fields: [
      { key: 'credentialId', label: 'Credential', type: 'text' },
      { key: 'token', label: 'Token override', type: 'text' },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { value: 'generic', label: 'Generic (method + path)' },
        { value: 'create_issue', label: 'Create issue' },
        { value: 'get_issue', label: 'Get issue' },
        { value: 'close_issue', label: 'Close issue' },
        { value: 'list_issues', label: 'List issues' },
        { value: 'update_issue', label: 'Update issue' },
        { value: 'add_comment', label: 'Add comment' },
        { value: 'create_pr', label: 'Create PR' },
        { value: 'get_pr', label: 'Get PR' },
        { value: 'list_prs', label: 'List PRs' },
        { value: 'get_repo', label: 'Get repo' },
        { value: 'list_repos', label: 'List repos' },
        { value: 'create_release', label: 'Create release' },
      ] },
      { key: 'owner', label: 'Owner', type: 'text' },
      { key: 'repo', label: 'Repo', type: 'text' },
      { key: 'issueNumber', label: 'Issue number', type: 'number' },
      { key: 'pullNumber', label: 'PR number', type: 'number' },
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'body', label: 'Body / comment', type: 'textarea' },
      { key: 'state', label: 'State', type: 'select', options: [{ value: 'open', label: 'Open' }, { value: 'closed', label: 'Closed' }] },
      { key: 'tagName', label: 'Tag name (release)', type: 'text' },
      { key: 'method', label: 'Method (generic)', type: 'select', options: [
        { value: 'GET', label: 'GET' },
        { value: 'POST', label: 'POST' },
        { value: 'PUT', label: 'PUT' },
        { value: 'PATCH', label: 'PATCH' },
        { value: 'DELETE', label: 'DELETE' },
      ] },
      { key: 'path', label: 'Path (generic)', type: 'text' },
    ],
  },
  {
    type: 'notion_api',
    category: 'data',
    label: 'Notion API',
    description: 'Call Notion API endpoints',
    color: SERVICE.notion,
    tint: 'service',
    serviceColor: SERVICE.notion,
    slug: 'NOTION',
    tag: 'API',
    subtitle: (c) => `${(c.method as string) || 'GET'} ${(c.path as string) || '/users/me'}`,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      credentialId: '',
      token: '',
      operation: 'generic',
      method: 'GET',
      path: '/users/me',
      body: '{}',
      notionVersion: '2022-06-28',
      pageId: '',
      blockId: '',
      databaseId: '',
      children: '[]',
      query: '',
      pageSize: 100,
    },
    fields: [
      { key: 'credentialId', label: 'Credential', type: 'text' },
      { key: 'token', label: 'Token override', type: 'text' },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { value: 'generic', label: 'Generic (method + path)' },
        { value: 'create_page', label: 'Create page' },
        { value: 'get_page', label: 'Get page' },
        { value: 'update_page', label: 'Update page' },
        { value: 'delete_page', label: 'Delete/archive page' },
        { value: 'append_block', label: 'Append blocks' },
        { value: 'list_pages', label: 'Query database' },
        { value: 'list_databases', label: 'List databases' },
        { value: 'get_database', label: 'Get database' },
        { value: 'search', label: 'Search' },
      ] },
      { key: 'pageId', label: 'Page ID', type: 'text' },
      { key: 'blockId', label: 'Block ID (append)', type: 'text' },
      { key: 'databaseId', label: 'Database ID', type: 'text' },
      { key: 'children', label: 'Children blocks JSON', type: 'code' },
      { key: 'query', label: 'Search query', type: 'text' },
      { key: 'pageSize', label: 'Page size', type: 'number' },
      { key: 'method', label: 'Method (generic)', type: 'select', options: [
        { value: 'GET', label: 'GET' },
        { value: 'POST', label: 'POST' },
        { value: 'PATCH', label: 'PATCH' },
        { value: 'DELETE', label: 'DELETE' },
      ] },
      { key: 'path', label: 'Path (generic)', type: 'text' },
      { key: 'body', label: 'Body JSON (generic)', type: 'code' },
      { key: 'notionVersion', label: 'Notion version', type: 'text' },
    ],
  },
  {
    type: 'airtable_records',
    category: 'data',
    label: 'Airtable Records',
    description: 'List, create, update, or delete Airtable records',
    color: SERVICE.airtable,
    tint: 'service',
    serviceColor: SERVICE.airtable,
    slug: 'AIR',
    tag: 'RECORDS',
    subtitle: (c) => `${(c.operation as string) || 'list'} ${(c.tableName as string) || 'table'}`,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      credentialId: '',
      token: '',
      operation: 'list',
      baseId: '',
      tableName: '',
      recordId: '',
      fieldsJson: '{}',
      recordsJson: '[]',
      filterByFormula: '',
      maxRecords: 100,
    },
    fields: [
      { key: 'credentialId', label: 'Credential', type: 'text' },
      { key: 'token', label: 'Token override', type: 'text' },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { value: 'list', label: 'List records' },
        { value: 'get', label: 'Get record' },
        { value: 'create', label: 'Create record' },
        { value: 'update', label: 'Update record' },
        { value: 'delete', label: 'Delete record' },
        { value: 'bulk_create', label: 'Bulk create' },
        { value: 'bulk_update', label: 'Bulk update' },
      ] },
      { key: 'baseId', label: 'Base ID', type: 'text' },
      { key: 'tableName', label: 'Table name', type: 'text' },
      { key: 'recordId', label: 'Record ID', type: 'text' },
      { key: 'fieldsJson', label: 'Fields JSON (create/update)', type: 'code' },
      { key: 'recordsJson', label: 'Records JSON (bulk)', type: 'code' },
      { key: 'filterByFormula', label: 'Filter formula', type: 'text' },
      { key: 'maxRecords', label: 'Max records', type: 'number' },
    ],
  },
  {
    type: 'graphql_request',
    category: 'data',
    label: 'GraphQL Request',
    description: 'Run a GraphQL query or mutation',
    color: SERVICE.graphql,
    tint: 'service',
    serviceColor: SERVICE.graphql,
    slug: 'GQL',
    tag: 'API',
    subtitle: (c) => (c.endpoint as string) || 'endpoint required',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      credentialId: '',
      endpoint: '',
      authHeader: 'Authorization',
      token: '',
      query: 'query Example {\n  __typename\n}',
      variablesJson: '{}',
    },
    fields: [
      { key: 'credentialId', label: 'Credential', type: 'text' },
      { key: 'endpoint', label: 'Endpoint', type: 'text' },
      { key: 'authHeader', label: 'Auth header', type: 'text' },
      { key: 'token', label: 'Token override', type: 'text' },
      { key: 'query', label: 'Query', type: 'code' },
      { key: 'variablesJson', label: 'Variables JSON', type: 'code' },
    ],
  },
  {
    type: 'csv_parse',
    category: 'data',
    label: 'CSV Parse',
    description: 'Convert CSV text into rows and items',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'CSV-IN',
    tag: 'TRANSFORM',
    subtitle: (c) => `delimiter ${(c.delimiter as string) || ','}`,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      text: '{{ input.data }}',
      sourceField: 'data',
      delimiter: ',',
      hasHeader: 'true',
      trim: 'true',
      columns: '',
    },
    fields: [
      { key: 'text', label: 'CSV text', type: 'textarea' },
      { key: 'sourceField', label: 'Source field fallback', type: 'text' },
      { key: 'delimiter', label: 'Delimiter', type: 'text' },
      { key: 'hasHeader', label: 'Header row', type: 'select', options: [
        { value: 'true', label: 'Yes' },
        { value: 'false', label: 'No' },
      ] },
      { key: 'trim', label: 'Trim cells', type: 'select', options: [
        { value: 'true', label: 'Yes' },
        { value: 'false', label: 'No' },
      ] },
      { key: 'columns', label: 'Columns without header', type: 'text' },
    ],
  },
  {
    type: 'csv_stringify',
    category: 'data',
    label: 'CSV Stringify',
    description: 'Convert rows or items into CSV text',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'CSV-OUT',
    tag: 'TRANSFORM',
    subtitle: (c) => `${(c.includeHeader as string) === 'false' ? 'no header' : 'header'} csv`,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      value: '{{ input.rows || input.items || input }}',
      sourceField: 'rows',
      delimiter: ',',
      includeHeader: 'true',
      columns: '',
    },
    fields: [
      { key: 'value', label: 'Rows value', type: 'textarea' },
      { key: 'sourceField', label: 'Source field fallback', type: 'text' },
      { key: 'delimiter', label: 'Delimiter', type: 'text' },
      { key: 'includeHeader', label: 'Include header', type: 'select', options: [
        { value: 'true', label: 'Yes' },
        { value: 'false', label: 'No' },
      ] },
      { key: 'columns', label: 'Columns', type: 'text' },
    ],
  },
  {
    type: 'xml_parse',
    category: 'data',
    label: 'XML Parse',
    description: 'Convert XML text into JSON',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'XML-IN',
    tag: 'TRANSFORM',
    subtitle: () => 'xml to json',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: { text: '{{ input.data }}', sourceField: 'data' },
    fields: [
      { key: 'text', label: 'XML text', type: 'textarea' },
      { key: 'sourceField', label: 'Source field fallback', type: 'text' },
    ],
  },
  {
    type: 'xml_stringify',
    category: 'data',
    label: 'XML Stringify',
    description: 'Convert JSON into XML text',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'XML-OUT',
    tag: 'TRANSFORM',
    subtitle: (c) => `<${(c.rootName as string) || 'root'}>`,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: { value: '{{ input.data || input }}', sourceField: 'data', rootName: 'root' },
    fields: [
      { key: 'value', label: 'JSON value', type: 'code' },
      { key: 'sourceField', label: 'Source field fallback', type: 'text' },
      { key: 'rootName', label: 'Root tag', type: 'text' },
    ],
  },
  {
    type: 'html_extract',
    category: 'data',
    label: 'HTML Extract',
    description: 'Extract text, HTML, or attributes from HTML',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'HTML',
    tag: 'TRANSFORM',
    subtitle: (c) => (c.selector as string) || 'title',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      html: '{{ input.html }}',
      sourceField: 'html',
      selector: 'title',
      attribute: 'text',
      multiple: 'false',
    },
    fields: [
      { key: 'html', label: 'HTML', type: 'textarea' },
      { key: 'sourceField', label: 'Source field fallback', type: 'text' },
      { key: 'selector', label: 'Selector', type: 'text' },
      { key: 'attribute', label: 'Return', type: 'select', options: [
        { value: 'text', label: 'Text' },
        { value: 'html', label: 'Inner HTML' },
        { value: 'href', label: 'href attribute' },
        { value: 'src', label: 'src attribute' },
        { value: 'content', label: 'content attribute' },
      ] },
      { key: 'multiple', label: 'Multiple matches', type: 'select', options: [
        { value: 'false', label: 'No' },
        { value: 'true', label: 'Yes' },
      ] },
    ],
  },
  {
    type: 'json_transform',
    category: 'data',
    label: 'JSON Transform',
    description: 'Get, set, pick, omit, parse, stringify, or merge JSON',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'JSON',
    tag: 'TRANSFORM',
    subtitle: (c) => (c.operation as string) || 'get',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      operation: 'get',
      value: '{{ input }}',
      sourceField: '',
      path: '',
      paths: '',
      setValue: '',
      space: 2,
    },
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { value: 'get', label: 'Get path' },
        { value: 'set', label: 'Set path' },
        { value: 'pick', label: 'Pick paths' },
        { value: 'omit', label: 'Omit paths' },
        { value: 'parse', label: 'Parse JSON' },
        { value: 'stringify', label: 'Stringify JSON' },
        { value: 'merge', label: 'Merge object' },
      ] },
      { key: 'value', label: 'Value', type: 'code' },
      { key: 'sourceField', label: 'Source field fallback', type: 'text' },
      { key: 'path', label: 'Path', type: 'text' },
      { key: 'paths', label: 'Paths', type: 'text' },
      { key: 'setValue', label: 'Set or merge value', type: 'code' },
      { key: 'space', label: 'Stringify spaces', type: 'number' },
    ],
  },
  {
    type: 'compression',
    category: 'data',
    label: 'Compression',
    description: 'Gzip, gunzip, deflate, or inflate text payloads',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'GZIP',
    tag: 'TRANSFORM',
    subtitle: (c) => (c.operation as string) || 'gzip',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      operation: 'gzip',
      value: '{{ input.data }}',
      sourceField: 'data',
      inputEncoding: 'utf8',
      outputEncoding: 'base64',
    },
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { value: 'gzip', label: 'Gzip' },
        { value: 'gunzip', label: 'Gunzip' },
        { value: 'deflate', label: 'Deflate' },
        { value: 'inflate', label: 'Inflate' },
      ] },
      { key: 'value', label: 'Value', type: 'textarea' },
      { key: 'sourceField', label: 'Source field fallback', type: 'text' },
      { key: 'inputEncoding', label: 'Input encoding', type: 'select', options: [
        { value: 'utf8', label: 'UTF-8' },
        { value: 'base64', label: 'Base64' },
      ] },
      { key: 'outputEncoding', label: 'Output encoding', type: 'select', options: [
        { value: 'base64', label: 'Base64' },
        { value: 'utf8', label: 'UTF-8' },
      ] },
    ],
  },
  {
    type: 'postgres_query',
    category: 'data',
    label: 'Postgres Query',
    description: 'Run a SQL query',
    color: SERVICE.postgres,
    tint: 'service',
    serviceColor: SERVICE.postgres,
    slug: 'PG',
    tag: 'ACTION',
    subtitle: (c) => {
      const q = (c.query as string) || '';
      const preview = q.replace(/\s+/g, ' ').trim().slice(0, 22);
      return preview.length < q.trim().length ? preview + '…' : preview || 'no query';
    },
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: { query: 'SELECT * FROM table WHERE id = $1', params: '[]' },
    fields: [
      { key: 'query', label: 'SQL Query', type: 'code' },
      { key: 'params', label: 'Parameters (JSON array)', type: 'code' },
    ],
  },
  {
    type: 'redis_get',
    category: 'data',
    label: 'Redis Get',
    description: 'Read a value from Redis',
    color: SERVICE.redis,
    tint: 'service',
    serviceColor: SERVICE.redis,
    slug: 'R-GET',
    tag: 'ACTION',
    subtitle: (c) => (c.key as string) || '{{ input.key }}',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: { key: '{{ input.key }}' },
    fields: [{ key: 'key', label: 'Key', type: 'text' }],
  },
  {
    type: 'redis_set',
    category: 'data',
    label: 'Redis Set',
    description: 'Write a value to Redis',
    color: SERVICE.redis,
    tint: 'service',
    serviceColor: SERVICE.redis,
    slug: 'R-SET',
    tag: 'ACTION',
    subtitle: (c) => `${(c.key as string) || 'key'} · ${(c.ttl as number) || 3600}s`,
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: { key: '{{ input.key }}', value: '{{ input.value }}', ttl: 3600 },
    fields: [
      { key: 'key', label: 'Key', type: 'text' },
      { key: 'value', label: 'Value', type: 'text' },
      { key: 'ttl', label: 'TTL (seconds)', type: 'number' },
    ],
  },
  {
    type: 'read_file',
    category: 'data',
    label: 'Read File',
    description: 'Read a workspace file into binary data',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'READ',
    tag: 'FILE',
    subtitle: (c) => (c.path as string) || 'path required',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: { path: '', binaryProperty: 'data', mimeType: '' },
    fields: [
      { key: 'path', label: 'Workspace file path', type: 'text' },
      { key: 'binaryProperty', label: 'Binary property', type: 'text' },
      { key: 'mimeType', label: 'MIME type override', type: 'text' },
    ],
  },
  {
    type: 'write_file',
    category: 'data',
    label: 'Write File',
    description: 'Write binary data to a workspace file',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'WRITE',
    tag: 'FILE',
    subtitle: (c) => (c.path as string) || 'input file name',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: { path: '', binaryProperty: 'data' },
    fields: [
      { key: 'path', label: 'Workspace file path', type: 'text' },
      { key: 'binaryProperty', label: 'Binary property', type: 'text' },
    ],
  },
  {
    type: 'move_binary_data',
    category: 'data',
    label: 'Move Binary Data',
    description: 'Convert JSON fields to binary data or binary data back to text',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'BINARY',
    tag: 'FILE',
    subtitle: (c) => (c.mode as string) || 'json_to_binary',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      mode: 'json_to_binary',
      sourceField: 'data',
      targetField: 'data',
      binaryProperty: 'data',
      fileName: 'data.txt',
      mimeType: 'text/plain',
      encoding: 'utf8',
    },
    fields: [
      { key: 'mode', label: 'Mode', type: 'select', options: [
        { value: 'json_to_binary', label: 'JSON to Binary' },
        { value: 'binary_to_json', label: 'Binary to JSON' },
      ] },
      { key: 'sourceField', label: 'Source field', type: 'text' },
      { key: 'targetField', label: 'Target field', type: 'text' },
      { key: 'binaryProperty', label: 'Binary property', type: 'text' },
      { key: 'fileName', label: 'File name', type: 'text' },
      { key: 'mimeType', label: 'MIME type', type: 'text' },
      { key: 'encoding', label: 'Encoding', type: 'select', options: [
        { value: 'utf8', label: 'UTF-8' },
        { value: 'base64', label: 'Base64' },
      ] },
    ],
  },
  {
    type: 'list_files',
    category: 'data',
    label: 'List Files',
    description: 'List files in the workspace file directory',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'LIST',
    tag: 'FILE',
    subtitle: (c) => (c.path as string) || '.',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      path: '.',
      recursive: 'false',
      includeDirectories: 'false',
      pattern: '*',
      maxDepth: 5,
      limit: 250,
    },
    fields: [
      { key: 'path', label: 'Workspace folder or file', type: 'text' },
      { key: 'pattern', label: 'Pattern', type: 'text' },
      { key: 'recursive', label: 'Recursive', type: 'select', options: [
        { value: 'false', label: 'No' },
        { value: 'true', label: 'Yes' },
      ] },
      { key: 'includeDirectories', label: 'Include directories', type: 'select', options: [
        { value: 'false', label: 'No' },
        { value: 'true', label: 'Yes' },
      ] },
      { key: 'maxDepth', label: 'Max depth', type: 'number' },
      { key: 'limit', label: 'Limit', type: 'number' },
    ],
  },
  {
    type: 'binary_metadata',
    category: 'data',
    label: 'Binary Metadata',
    description: 'Inspect binary data references without downloading file content',
    color: '#A1A1AA',
    tint: 'neutral',
    slug: 'META',
    tag: 'FILE',
    subtitle: (c) => (c.source as string) || 'input',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      source: 'input',
      binaryProperty: 'data',
      binaryId: '',
      lookup: 'true',
      limit: 50,
      fileNameContains: '',
      mimeType: '',
    },
    fields: [
      { key: 'source', label: 'Source', type: 'select', options: [
        { value: 'input', label: 'Input binary property' },
        { value: 'id', label: 'Binary ID' },
        { value: 'recent', label: 'Recent binary data' },
      ] },
      { key: 'binaryProperty', label: 'Binary property', type: 'text' },
      { key: 'binaryId', label: 'Binary ID', type: 'text' },
      { key: 'lookup', label: 'Look up database metadata', type: 'select', options: [
        { value: 'true', label: 'Yes' },
        { value: 'false', label: 'Use input reference only' },
      ] },
      { key: 'limit', label: 'Recent limit', type: 'number' },
      { key: 'fileNameContains', label: 'File name contains', type: 'text' },
      { key: 'mimeType', label: 'MIME type filter', type: 'text' },
    ],
  },
  {
    type: 's3_object',
    category: 'data',
    label: 'S3 Object',
    description: 'List, upload, download, inspect, or delete S3-compatible objects',
    color: SERVICE.s3,
    tint: 'service',
    serviceColor: SERVICE.s3,
    slug: 'S3',
    tag: 'STORAGE',
    subtitle: (c) => `${(c.operation as string) || 'list'} ${(c.key as string) || (c.prefix as string) || ''}`.trim(),
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      operation: 'list',
      credentialId: '',
      endpoint: '',
      region: 'us-east-1',
      bucket: '',
      key: '',
      prefix: '',
      maxKeys: 100,
      sourceMode: 'text',
      value: '{{ input.data }}',
      sourceField: 'data',
      binaryProperty: 'data',
      fileName: '',
      contentType: 'application/octet-stream',
      forcePathStyle: 'true',
    },
    fields: [
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { value: 'list', label: 'List objects' },
        { value: 'get', label: 'Download object' },
        { value: 'put', label: 'Upload object' },
        { value: 'head', label: 'Get metadata' },
        { value: 'delete', label: 'Delete object' },
      ] },
      { key: 'credentialId', label: 'Credential', type: 'text' },
      { key: 'endpoint', label: 'Endpoint override', type: 'text' },
      { key: 'region', label: 'Region', type: 'text' },
      { key: 'bucket', label: 'Bucket', type: 'text' },
      { key: 'key', label: 'Object key', type: 'text' },
      { key: 'prefix', label: 'List prefix', type: 'text' },
      { key: 'maxKeys', label: 'Max keys', type: 'number' },
      { key: 'sourceMode', label: 'Upload source', type: 'select', options: [
        { value: 'text', label: 'Text/value' },
        { value: 'binary', label: 'Binary property' },
      ] },
      { key: 'value', label: 'Upload value', type: 'textarea' },
      { key: 'sourceField', label: 'Upload source field', type: 'text' },
      { key: 'binaryProperty', label: 'Binary property', type: 'text' },
      { key: 'fileName', label: 'Downloaded file name', type: 'text' },
      { key: 'contentType', label: 'Upload content type', type: 'text' },
      { key: 'forcePathStyle', label: 'Path style URLs', type: 'select', options: [
        { value: 'true', label: 'Yes' },
        { value: 'false', label: 'No' },
      ] },
    ],
  },
  {
    type: 'salesforce_api',
    category: 'data',
    label: 'Salesforce API',
    description: 'Query and manage Salesforce CRM records via REST API',
    color: SERVICE.salesforce,
    tint: 'service',
    serviceColor: SERVICE.salesforce,
    slug: 'SF',
    tag: 'CRM',
    subtitle: (c) => (c.operation as string) || 'query',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      credentialId: '',
      instanceUrl: '',
      operation: 'query',
      sobject: 'Account',
      soql: 'SELECT Id, Name FROM Account LIMIT 10',
      recordId: '',
      fields: '',
    },
    fields: [
      { key: 'credentialId', label: 'Credential', type: 'text' },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { value: 'query',         label: 'SOQL Query' },
        { value: 'get_record',    label: 'Get Record' },
        { value: 'create_record', label: 'Create Record' },
        { value: 'update_record', label: 'Update Record' },
        { value: 'delete_record', label: 'Delete Record' },
      ] },
      { key: 'instanceUrl', label: 'Instance URL', type: 'text', placeholder: 'https://myorg.salesforce.com' },
      { key: 'sobject', label: 'sObject type', type: 'text', placeholder: 'Account' },
      { key: 'soql', label: 'SOQL query', type: 'textarea' },
      { key: 'recordId', label: 'Record ID', type: 'text' },
      { key: 'fields', label: 'Fields (JSON)', type: 'textarea' },
    ],
  },
  {
    type: 'hubspot_api',
    category: 'data',
    label: 'HubSpot API',
    description: 'Manage HubSpot CRM contacts and deals',
    color: SERVICE.hubspot,
    tint: 'service',
    serviceColor: SERVICE.hubspot,
    slug: 'HS',
    tag: 'CRM',
    subtitle: (c) => (c.operation as string) || 'list_contacts',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      credentialId: '',
      operation: 'list_contacts',
      contactId: '',
      properties: '',
      dealProperties: '',
      limit: 10,
    },
    fields: [
      { key: 'credentialId', label: 'Credential', type: 'text' },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { value: 'list_contacts',  label: 'List contacts' },
        { value: 'get_contact',    label: 'Get contact' },
        { value: 'create_contact', label: 'Create contact' },
        { value: 'update_contact', label: 'Update contact' },
        { value: 'create_deal',    label: 'Create deal' },
        { value: 'list_deals',     label: 'List deals' },
      ] },
      { key: 'contactId', label: 'Contact ID', type: 'text' },
      { key: 'properties', label: 'Contact properties (JSON)', type: 'textarea' },
      { key: 'dealProperties', label: 'Deal properties (JSON)', type: 'textarea' },
      { key: 'limit', label: 'Limit', type: 'number' },
    ],
  },
  {
    type: 'linear_api',
    category: 'data',
    label: 'Linear API',
    description: 'Manage Linear issues, teams, and projects via GraphQL',
    color: SERVICE.linear,
    tint: 'service',
    serviceColor: SERVICE.linear,
    slug: 'LIN',
    tag: 'PM',
    subtitle: (c) => (c.operation as string) || 'list_issues',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {
      credentialId: '',
      operation: 'list_issues',
      issueId: '',
      issueTitle: '',
      description: '',
      teamId: '',
      stateId: '',
      limit: 25,
    },
    fields: [
      { key: 'credentialId', label: 'Credential', type: 'text' },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { value: 'list_issues',  label: 'List issues' },
        { value: 'get_issue',    label: 'Get issue' },
        { value: 'create_issue', label: 'Create issue' },
        { value: 'update_issue', label: 'Update issue' },
        { value: 'list_teams',   label: 'List teams' },
      ] },
      { key: 'issueId', label: 'Issue ID', type: 'text' },
      { key: 'issueTitle', label: 'Issue title', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'teamId', label: 'Team ID', type: 'text' },
      { key: 'stateId', label: 'State ID', type: 'text' },
      { key: 'limit', label: 'Limit', type: 'number' },
    ],
  },
];

export const NODE_TYPE_MAP = Object.fromEntries(NODE_TYPE_DEFS.map(d => [d.type, d]));

export function getNodeDef(type: string): NodeTypeDef {
  if (type === 'placeholder') {
    return {
      type: 'placeholder',
      category: 'core' as const,
      label: 'Unsupported n8n Node',
      description: 'Imported node with no executable Otto equivalent yet',
      color: '#ef4444',
      tint: 'service',
      serviceColor: '#ef4444',
      slug: 'TODO',
      tag: 'BLOCKED',
      subtitle: (config) => (config.n8nOriginalType as string) || 'replace before run',
      handles: {
        in: [{ id: 'input' }],
        out: [{ id: 'output' }],
      },
      defaultConfig: {},
      fields: [],
    };
  }
  return NODE_TYPE_MAP[type] ?? {
    type,
    category: 'core' as const,
    label: type,
    description: '',
    color: '#64748b',
    handles: {
      in: [{ id: 'input' }],
      out: [{ id: 'output' }],
    },
    defaultConfig: {},
    fields: [],
  };
}
